# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestmove',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bestmove',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
