# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20171108_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestmove',
            name='replicated',
            field=models.BooleanField(default=False),
        ),
    ]
