version: "3"
services:
  balancer:
    build:
      context: ..
      dockerfile: environment/Dockerfile_nginx
    image: "nginx:balancer"
    ports:
      - "${NNREVERSI_HOST_PORT}:80"
    command:
      - "/usr/sbin/nginx"
      - "-g"
      - "daemon off;"

  nnreversi:
    build:
      context: ..
      dockerfile: environment/Dockerfile
    image: "python:django"
    volumes:
      - "../django:/opt/NNReversi/django"
    environment:
      - "DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}"
      - "NNREVERSI_DB_HOSTNAME=${NNREVERSI_DB_HOSTNAME}"
      - "NNREVERSI_DB_DATABASE=${NNREVERSI_DB_DATABASE}"
      - "NNREVERSI_DB_USERNAME=${NNREVERSI_DB_USERNAME}"
      - "NNREVERSI_DB_PASSWORD=${NNREVERSI_DB_PASSWORD}"
      - "NNREVERSI_DB_PORT=${NNREVERSI_DB_PORT}"
      - "NNREVERSI_DJANGO_HOSTNAME=${NNREVERSI_DJANGO_HOSTNAME}"
      - "NNREVERSI_DJANGO_PORT=${NNREVERSI_DJANGO_PORT}"
    command:
      - "bash"
      - "-c"
      - "sleep 10 && . /opt/NNReversi/venv/bin/activate && python manage.py migrate && service nginx restart && uwsgi --ini /opt/NNReversi/django/mysite/uwsgi.ini"
  db:
    image: "mysql:5.7"
    container_name: "db"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=root"
    volumes:
      - "db:/var/lib/mysql"
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
volumes:
  db:
    driver: "local"
