# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20171108_2048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bestmove',
            unique_together=set([('first_half_arrangement', 'last_half_arrangement')]),
        ),
    ]
