import os

NNREVERSI_DJANGO_HOSTNAME = os.environ['NNREVERSI_DJANGO_HOSTNAME']
NNREVERSI_DJANGO_PORT = os.environ['NNREVERSI_DJANGO_PORT']

ENDPOINT_URL = "http://" + NNREVERSI_DJANGO_HOSTNAME + ":" + NNREVERSI_DJANGO_PORT
